### ISSUE TITLE
[UI] Add Search Box

### ISSUE THREAD

**Issue by cbclemmer** [cbclemmer/discovery_park_map#23]
**Requirements:**
- Add a search box to the top of the app
- Add a function to the Main_Controller called Open_Search which should:
    - Change the AppState to Search
    - Hide all current UI elements
    - Show the search at the top
    - Show a white background
- When the text in the search changes, the Main_Controller::Search_Nodes function should fire with the current text in the box as input
- Use the result of Search_Nodes to create a list of items one for each result in the UI under the search box
- Add a cancel button on the right side of the search box

requires #22, #21, #18

**Comment by cbclemmer** [comment]
@TheWaterMage 2 hour session 10/20

**Comment by TheWaterMage** [comment]
56m

**Comment by TheWaterMage** [comment]
30m fixing search function and altering search_node function

**Comment by cbclemmer** [comment]
PR #70 closed this issue
